/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f407xx_gpio_driver.h"
#include "stm32f407xx.h"


int main(void)
{
	GPIO_Handle_t *pGPIOHandle;
	pGPIOHandle->pGPIOx = GPIOA;
    /* Loop forever */
	//Just giving commands
	for(;;);
}
